# Generated by Django 3.2.9 on 2021-12-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0007_auto_20211215_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
